/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera, PerspectiveCamera } from '@react-three/drei'
import { useEffect } from 'react'



export default function Robot({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/vBucYTlvT-4Jiu7j/scene.splinecode');

  useEffect(() => {
    console.log(nodes, materials)
    }
    , [nodes, materials]);

  return (
    <>
      {/* <color attach="background" args={['#f2f2f2']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <PerspectiveCamera
            name="Camera 2"
            makeDefault={true}
            zoom={2}
            far={100000}
            near={70}
            fov={45}
            position={[0, 248.98, 360]}
            rotation={[0.01, 0, 0]}
          />
          <pointLight
            name="Point Light"
            castShadow
            intensity={5}
            distance={2000}
            shadow-mapSize-width={2048}
            shadow-mapSize-height={2048}
            shadow-camera-near={100}
            shadow-camera-far={100000}
            position={[-595, 579, -393]}
          />
          <group name="Bot" position={[-6.75, 76.68, 4]} scale={0.8}>
            <group name="Top part" position={[-0.18, 58.95, 2.04]}>
              <group name="Head" position={[0.18, 183.55, 18.62]}>
                <mesh
                  name="Head 2"
                  geometry={nodes['Head 2'].geometry}
                  material={materials.Head}
                  castShadow
                  receiveShadow
                  position={[0, 42.94, 4]}
                />
              </group>
              <group name="Neck" position={[0.18, 189.77, 5.25]}>
                <mesh
                  name="Cube"
                  geometry={nodes.Cube.geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[0, -13.24, -0.35]}
                  rotation={[0.12, 0, 0]}
                  scale={1.25}
                />
                <mesh
                  name="Cylinder 3"
                  geometry={nodes['Cylinder 3'].geometry}
                  material={materials.Body}
                  castShadow
                  receiveShadow
                  position={[0, -34.32, -3.15]}
                  rotation={[0.21, 0, 0]}
                  scale={1}
                />
                <group name="Group 3" position={[0, -9.41, -0.65]} rotation={[0.43, 0, 0]}>
                  <group name="Group 2" position={[20.6, 0, 0]} scale={[-1, 1, 1]}>
                    <mesh
                      name="Cylinder 4"
                      geometry={nodes['Cylinder 4'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      rotation={[0.13, 0, -0.28]}
                      scale={1}
                    />
                  </group>
                  <group name="Group" position={[-20.6, 0, 0]}>
                    <mesh
                      name="Cylinder 41"
                      geometry={nodes['Cylinder 41'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[0, 0, 0]}
                      rotation={[0.13, 0, -0.28]}
                      scale={1}
                    />
                  </group>
                </group>
                <mesh
                  name="Cylinder"
                  geometry={nodes.Cylinder.geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[0, 12.03, 4.41]}
                  rotation={[0.13, 0, 0]}
                  scale={1}
                />
              </group>
              <group name="Hand Instance" position={[-112.74, 26.23, 1.71]} scale={[-1, 1, 1]}>
                <group name="Hand LEFT" position={[-40.59, 98.31, -3.47]} rotation={[0, 0, 0.09]} scale={1}>
                  <group name="arm" position={[24.87, 7.43, 2.2]}>
                    <group name="elbow" position={[20.54, -85.63, 2.66]} rotation={[0, -0.14, 0]} scale={1}>
                      <group name="Group1" position={[-0.75, -0.02, -0.39]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh
                          name="Rectangle 3"
                          geometry={nodes['Rectangle 3'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[1.63, -2.93, 1.69]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Ellipse 3"
                          geometry={nodes['Ellipse 3'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[0.02, 22.11, -8.15]}
                          rotation={[1.21, 0, 0.06]}
                          scale={1}
                        />
                      </group>
                      <group name="forearm" position={[-4.79, -12.26, 1.36]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh
                          name="Hand"
                          geometry={nodes.Hand.geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-9.43, -91.2, 36.55]}
                          rotation={[0.28, 0.94, 2.48]}
                          scale={[-1.4, 1.4, 1.4]}
                        />
                        <mesh
                          name="Ellipse 5"
                          geometry={nodes['Ellipse 5'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-7.61, -0.81, -0.89]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Rectangle 4"
                          geometry={nodes['Rectangle 4'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-4.1, -8.12, 1.67]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Ellipse 4"
                          geometry={nodes['Ellipse 4'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[3.99, -14.41, 4.28]}
                          rotation={[1.21, 0, 0.06]}
                          scale={1}
                        />
                        <mesh
                          name="Cube 3"
                          geometry={nodes['Cube 3'].geometry}
                          material={materials.Body}
                          castShadow
                          receiveShadow
                          position={[-0.42, -62.58, 23.36]}
                          rotation={[1, 1.41, -1.44]}
                          scale={1}
                        />
                      </group>
                    </group>
                    <mesh
                      name="Cube 2"
                      geometry={nodes['Cube 2'].geometry}
                      material={materials.Body}
                      castShadow
                      receiveShadow
                      position={[23.34, -26.19, -4.77]}
                      rotation={[0, 0, 0.37]}
                      scale={1}
                    />
                  </group>
                  <mesh
                    name="Ellipse 6"
                    geometry={nodes['Ellipse 6'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[15.04, 1.44, -2.58]}
                    rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]}
                    scale={1}
                  />
                  <mesh
                    name="Ellipse 2"
                    geometry={nodes['Ellipse 2'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[13.39, 1.26, -2.58]}
                    rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 2"
                    geometry={nodes['Rectangle 2'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[3.27, -0.39, -7.25]}
                    rotation={[0, 0, -3.03]}
                    scale={1}
                  />
                </group>
              </group>
              <group name="Hand1" position={[112.74, 26.23, 1.71]}>
                <group name="Hand LEFT1" position={[-40.59, 98.31, -3.47]} rotation={[0, 0, 0.09]} scale={1}>
                  <group name="arm1" position={[24.87, 7.43, 2.2]}>
                    <group name="elbow1" position={[20.54, -85.63, 2.66]} rotation={[0, -0.14, 0]} scale={1}>
                      <group name="Group2" position={[-0.75, -0.02, -0.39]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh
                          name="Rectangle 31"
                          geometry={nodes['Rectangle 31'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[1.63, -2.93, 1.69]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Ellipse 31"
                          geometry={nodes['Ellipse 31'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[0.02, 22.11, -8.15]}
                          rotation={[1.21, 0, 0.06]}
                          scale={1}
                        />
                      </group>
                      <group name="forearm1" position={[-4.79, -12.26, 1.36]} rotation={[0.32, 0, 0]} scale={1}>
                        <mesh
                          name="Hand2"
                          geometry={nodes.Hand2.geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-9.43, -91.2, 36.55]}
                          rotation={[0.28, 0.94, 2.48]}
                          scale={[-1.4, 1.4, 1.4]}
                        />
                        <mesh
                          name="Ellipse 51"
                          geometry={nodes['Ellipse 51'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-7.61, -0.81, -0.89]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Rectangle 41"
                          geometry={nodes['Rectangle 41'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[-4.1, -8.12, 1.67]}
                          rotation={[-0.75, 1.54, 0.4]}
                          scale={1}
                        />
                        <mesh
                          name="Ellipse 41"
                          geometry={nodes['Ellipse 41'].geometry}
                          material={materials.Parts}
                          castShadow
                          receiveShadow
                          position={[3.99, -14.41, 4.28]}
                          rotation={[1.21, 0, 0.06]}
                          scale={1}
                        />
                        <mesh
                          name="Cube 31"
                          geometry={nodes['Cube 31'].geometry}
                          material={materials.Body}
                          castShadow
                          receiveShadow
                          position={[-0.42, -62.58, 23.36]}
                          rotation={[1, 1.41, -1.44]}
                          scale={1}
                        />
                      </group>
                    </group>
                    <mesh
                      name="Cube 21"
                      geometry={nodes['Cube 21'].geometry}
                      material={materials.Body}
                      castShadow
                      receiveShadow
                      position={[23.34, -26.19, -4.77]}
                      rotation={[0, 0, 0.37]}
                      scale={1}
                    />
                  </group>
                  <mesh
                    name="Ellipse 61"
                    geometry={nodes['Ellipse 61'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[15.04, 1.44, -2.58]}
                    rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]}
                    scale={1}
                  />
                  <mesh
                    name="Ellipse 21"
                    geometry={nodes['Ellipse 21'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[13.39, 1.26, -2.58]}
                    rotation={[-Math.PI / 2, 1.47, -Math.PI / 2]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 21"
                    geometry={nodes['Rectangle 21'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[3.27, -0.39, -7.25]}
                    rotation={[0, 0, -3.03]}
                    scale={1}
                  />
                </group>
              </group>
              <mesh
                name="Body"
                geometry={nodes.Body.geometry}
                material={materials.Body}
                castShadow
                receiveShadow
                position={[0.18, -111.86, 10.7]}
              >
                <group name="Group3" position={[-67.84, 234.76, -10.06]} rotation={[0, 0, -0.09]} scale={[-1, 1, 1]}>
                  <mesh
                    name="Ellipse"
                    geometry={nodes.Ellipse.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[3.58, 0.58, -10.71]}
                    rotation={[0, 0, 0.1]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle"
                    geometry={nodes.Rectangle.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, -0.74]}
                    rotation={[0, 0, 0.11]}
                    scale={1}
                  />
                </group>
                <group name="Group4" position={[67.82, 234.79, -10.06]} rotation={[0, 0, 0.09]} scale={1}>
                  <mesh
                    name="Ellipse1"
                    geometry={nodes.Ellipse1.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[3.58, 0.58, -10.71]}
                    rotation={[0, 0, 0.1]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle1"
                    geometry={nodes.Rectangle1.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, -0.74]}
                    rotation={[0, 0, 0.11]}
                  />
                </group>
              </mesh>
            </group>
            <group name="Bottom" position={[1.37, 24.24, 4.71]}>
              <group name="Group 4" position={[-1.37, 43.1, 4.06]}>
                <group name="Group 21" position={[20.6, 0, 0]} scale={[-1, 1, 1]}>
                  <mesh
                    name="Cylinder 42"
                    geometry={nodes['Cylinder 42'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    rotation={[0.13, 0, -0.28]}
                    scale={1}
                  />
                </group>
                <group name="Group5" position={[-20.6, 0, 0]}>
                  <mesh
                    name="Cylinder 43"
                    geometry={nodes['Cylinder 43'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, 0]}
                    rotation={[0.13, 0, -0.28]}
                    scale={1}
                  />
                </group>
              </group>
              <group
                name="Leg Left Instance"
                position={[-49.1, 2.78, 23.6]}
                rotation={[0.13, -0.33, 0]}
                scale={[-1, 1, 1]}
              >
                <group name="femur" position={[2.57, -66.67, 0.63]}>
                  <mesh
                    name="Cube 32"
                    geometry={nodes['Cube 32'].geometry}
                    material={materials.Body}
                    castShadow
                    receiveShadow
                    position={[-0.7, -51.54, -1.8]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 9"
                    geometry={nodes['Rectangle 9'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-2.54, -2.13, -2.26]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 10"
                    geometry={nodes['Rectangle 10'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-9.7, -92.9, -2.26]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <group name="shin" position={[-2.57, -114.51, -2.91]} rotation={[-0.14, 0, 0]}>
                    <group name="Foot" position={[0, -160.39, -18.69]}>
                      <mesh
                        name="Cube 5"
                        geometry={nodes['Cube 5'].geometry}
                        material={materials.Parts}
                        castShadow
                        receiveShadow
                        position={[1.31, -9.36, 18.24]}
                        rotation={[0.01, -0.14, 0]}
                        scale={1}
                      />
                    </group>
                    <mesh
                      name="Ellipse 52"
                      geometry={nodes['Ellipse 52'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[2.81, -61.16, -29.89]}
                      rotation={[1.45, 0, Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Cube 4"
                      geometry={nodes['Cube 4'].geometry}
                      material={materials.Body}
                      castShadow
                      receiveShadow
                      position={[1.26, -76.59, 0.28]}
                      rotation={[1.58, 0, -Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Ellipse 42"
                      geometry={nodes['Ellipse 42'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[1.31, -12.67, 0.86]}
                      rotation={[1.58, 0, -Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Rectangle 12"
                      geometry={nodes['Rectangle 12'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[7.78, -10.93, 0.55]}
                      rotation={[-1.56, Math.PI / 2, 0]}
                      scale={1}
                    />
                    <mesh
                      name="Rectangle 11"
                      geometry={nodes['Rectangle 11'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[-18.02, -10.93, 0.55]}
                      rotation={[-1.56, Math.PI / 2, 0]}
                      scale={1}
                    />
                  </group>
                </group>
                <mesh
                  name="Ellipse 32"
                  geometry={nodes['Ellipse 32'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[1.28, -29.42, -1.28]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Ellipse 22"
                  geometry={nodes['Ellipse 22'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[1.28, -23.29, -1.28]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Rectangle 8"
                  geometry={nodes['Rectangle 8'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[-11.82, -51.34, -1.62]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 7"
                  geometry={nodes['Rectangle 7'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[-2.68, -9.71, 0.03]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={1}
                />
              </group>
              <group name="Leg Left" position={[49.1, 2.78, 23.6]} rotation={[0.13, 0.31, 0]}>
                <group name="femur1" position={[2.57, -66.67, 0.63]}>
                  <mesh
                    name="Cube 33"
                    geometry={nodes['Cube 33'].geometry}
                    material={materials.Body}
                    castShadow
                    receiveShadow
                    position={[-0.7, -51.54, -1.8]}
                    rotation={[Math.PI / 2, 0, -Math.PI]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 91"
                    geometry={nodes['Rectangle 91'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-2.54, -2.13, -2.26]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <mesh
                    name="Rectangle 101"
                    geometry={nodes['Rectangle 101'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-9.7, -92.9, -2.26]}
                    rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <group name="shin1" position={[-2.57, -114.51, -2.91]} rotation={[-0.14, 0, 0]}>
                    <group name="Foot1" position={[0, -160.39, -18.69]}>
                      <mesh
                        name="Cube 51"
                        geometry={nodes['Cube 51'].geometry}
                        material={materials.Parts}
                        castShadow
                        receiveShadow
                        position={[1.31, -9.36, 18.24]}
                        rotation={[0.01, -0.14, 0]}
                        scale={1}
                      />
                    </group>
                    <mesh
                      name="Ellipse 53"
                      geometry={nodes['Ellipse 53'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[2.81, -61.16, -29.89]}
                      rotation={[1.45, 0, Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Cube 41"
                      geometry={nodes['Cube 41'].geometry}
                      material={materials.Body}
                      castShadow
                      receiveShadow
                      position={[1.26, -76.59, 0.28]}
                      rotation={[1.58, 0, -Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Ellipse 43"
                      geometry={nodes['Ellipse 43'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[1.31, -12.67, 0.86]}
                      rotation={[1.58, 0, -Math.PI]}
                      scale={1}
                    />
                    <mesh
                      name="Rectangle 121"
                      geometry={nodes['Rectangle 121'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[7.78, -10.93, 0.55]}
                      rotation={[-1.56, Math.PI / 2, 0]}
                      scale={1}
                    />
                    <mesh
                      name="Rectangle 111"
                      geometry={nodes['Rectangle 111'].geometry}
                      material={materials.Parts}
                      castShadow
                      receiveShadow
                      position={[-18.02, -10.93, 0.55]}
                      rotation={[-1.56, Math.PI / 2, 0]}
                      scale={1}
                    />
                  </group>
                </group>
                <mesh
                  name="Ellipse 33"
                  geometry={nodes['Ellipse 33'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[1.28, -29.42, -1.28]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Ellipse 23"
                  geometry={nodes['Ellipse 23'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[1.28, -23.29, -1.28]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Rectangle 81"
                  geometry={nodes['Rectangle 81'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[-11.82, -51.34, -1.62]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={1}
                />
                <mesh
                  name="Rectangle 71"
                  geometry={nodes['Rectangle 71'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[-2.68, -9.71, 0.03]}
                  rotation={[Math.PI / 2, Math.PI / 2, 0]}
                  scale={1}
                />
              </group>
              <group name="Pelvic" position={[-1.37, 13.5, -0.96]}>
                <group name="Group 22" position={[-45.45, -13.75, 14.79]} scale={[-1, 1, 1]}>
                  <mesh
                    name="Rectangle 5"
                    geometry={nodes['Rectangle 5'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-15.65, 1.41, 1.52]}
                    rotation={[Math.PI, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <mesh
                    name="Ellipse2"
                    geometry={nodes.Ellipse2.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, -21.97]}
                    rotation={[0, 0, -Math.PI]}
                    scale={1}
                  />
                </group>
                <group name="Group6" position={[48.59, -13.75, 14.79]}>
                  <mesh
                    name="Rectangle 51"
                    geometry={nodes['Rectangle 51'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[-15.65, 1.41, 1.52]}
                    rotation={[Math.PI, Math.PI / 2, 0]}
                    scale={1}
                  />
                  <mesh
                    name="Ellipse3"
                    geometry={nodes.Ellipse3.geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[0, 0, -21.97]}
                    rotation={[0, 0, -Math.PI]}
                    scale={1}
                  />
                </group>
                <mesh
                  name="Rectangle 42"
                  geometry={nodes['Rectangle 42'].geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[0, -13.17, -5.53]}
                  rotation={[-Math.PI, 0, 0]}
                  scale={[1, 0.88, 1]}
                />
                <group name="Group 31" position={[0, -13.17, 0.66]}>
                  <mesh
                    name="Rectangle 32"
                    geometry={nodes['Rectangle 32'].geometry}
                    material={materials.Parts}
                    castShadow
                    receiveShadow
                    position={[25.71, 0, 0]}
                    rotation={[Math.PI / 2, -Math.PI / 2, 0]}
                    scale={[1, 0.88, 1]}
                  />
                </group>
                <mesh
                  name="Rectangle2"
                  geometry={nodes.Rectangle2.geometry}
                  material={materials.Parts}
                  castShadow
                  receiveShadow
                  position={[0, 61.49, 0.66]}
                  rotation={[Math.PI / 2, 0, 0]}
                />
              </group>
            </group>
          </group>
          <OrthographicCamera name="1" makeDefault={false} far={10000} near={-50000} />
        </scene>
      </group> */}
    </>
  )
}
